<a href="https://colab.research.google.com/github/GautamChy/Data-Science-Journey/blob/main/PandasDay03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'salary' : np.random.randint(30000, 120000, 100000)
})

In [ ]:
df.shape

(100000, 1)

In [ ]:
df.head()

   salary
0  115338
1   43646
2   72775
3   59383
4   37636

In [ ]:
# This way takes more time
result = []
for val in df['salary']:
  result.append(val * 1.1)
df['new_salary'] = result      # new_salary means new column store a value by result

In [ ]:
# Vectorized opearation
# This way take less time
# Arithmetic
df['tax'] = df['salary'] * 0.25    # tax is new column, salary is old column so salary * 0.25
df['bonus'] = df['salary'] * 0.1
df['net']   = df['salary'] - df['tax']
df['ratio'] =df['salary'] / df['bonus']

In [ ]:
df

       salary  new_salary       tax    bonus       net  ratio
0      115338    126871.8  28834.50  11533.8  86503.50   10.0
1       43646     48010.6  10911.50   4364.6  32734.50   10.0
2       72775     80052.5  18193.75   7277.5  54581.25   10.0
3       59383     65321.3  14845.75   5938.3  44537.25   10.0
4       37636     41399.6   9409.00   3763.6  28227.00   10.0
...       ...         ...       ...      ...       ...    ...
99995   74156     81571.6  18539.00   7415.6  55617.00   10.0
99996  103788    114166.8  25947.00  10378.8  77841.00   10.0
99997   87281     96009.1  21820.25   8728.1  65460.75   10.0
99998   71685     78853.5  17921.25   7168.5  53763.75   10.0
99999   54308     59738.8  13577.00   5430.8  40731.00   10.0

[100000 rows x 6 columns]