<a href="https://colab.research.google.com/github/GautamChy/Data-Science/blob/main/38_Suppport_Vector_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Dataset (Tips Dataset)
import seaborn as sns
df = sns.load_dataset('tips')

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [ ]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# making dependent features
X = df.drop('total_bill', axis = 1)
y = df['total_bill']

In [ ]:
# Independent features
X.head()

    tip     sex smoker  day    time  size
0  1.01  Female     No  Sun  Dinner     2
1  1.66    Male     No  Sun  Dinner     3
2  3.50    Male     No  Sun  Dinner     3
3  3.31    Male     No  Sun  Dinner     2
4  3.61  Female     No  Sun  Dinner     4

In [ ]:
# Dependent features
y.head()

0    16.99
1    10.34
2    21.01
3    23.68
4    24.59
Name: total_bill, dtype: float64

In [ ]:
# Train Test Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.25,random_state = 20)

In [ ]:
x_train.head()

       tip   sex smoker   day    time  size
122   2.50  Male     No  Thur   Lunch     2
80    3.00  Male    Yes  Thur   Lunch     2
63    3.76  Male    Yes   Sat  Dinner     4
50    2.50  Male     No   Sun  Dinner     2
170  10.00  Male    Yes   Sat  Dinner     3

# Feature Encoding(Label Encoding and One Hot Encoding)
* Convert above column value into Numerical data
i.e Male 1

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [ ]:
# fit ( only do in training)
x_train['sex'] = le1.fit_transform(x_train['sex'])
x_train['smoker'] = le2.fit_transform(x_train['smoker'])
x_train['time'] = le3.fit_transform(x_train['time'])

In [ ]:
x_train.head()

       tip  sex  smoker   day  time  size
122   2.50    1       0  Thur     1     2
80    3.00    1       1  Thur     1     2
63    3.76    1       1   Sat     0     4
50    2.50    1       0   Sun     0     2
170  10.00    1       1   Sat     0     3

In [ ]:
# Nover do fit in testing
x_test['sex'] = le1.transform(x_test['sex'])
x_test['smoker'] = le2.transform(x_test['smoker'])
x_test['time'] = le3.transform(x_test['time'])

In [ ]:
## One Hot Encoding -- Column Transformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('onehot', OneHotEncoder(drop = 'first'), [3])], remainder = 'passthrough')

In [ ]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
x_train = ct.fit_transform(x_train)
x_train

array([[ 0.  ,  0.  ,  1.  ,  2.5 ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  3.  ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.76,  1.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  2.5 ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.  ,  1.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.5 ,  0.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  5.  ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  3.4 ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.64,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  5.  ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.16,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  6.5 ,  1.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  3.55,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.52,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  4.  ,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.47,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  4.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.  ,  0.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.09,  0.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  5.  ,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  3.76,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.08,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  ,  2.5 ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  4.08,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.2 ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  5.92,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  1.57,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.6 ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.48,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  3.15,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  3.51,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.  ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  6.5 ,  0.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  2.75,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.03,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.48,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.03,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  5.17,  0.  ,  0.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  3.  ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.5 ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.58,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  3.48,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  4.  ,  1.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  3.6 ,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  1.25,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.07,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.14,  0.  ,  0.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  1.44,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  4.29,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.01,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.07,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.76,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.01,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.24,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.  ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  5.85,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.45,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  3.25,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.54,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  4.19,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  2.2 ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.5 ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  1.5 ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.09,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.55,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  1.48,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  4.2 ,  0.  ,  0.  ,  1.  ,  6.  ],
       [ 0.  ,  0.  ,  1.  ,  4.  ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  3.02,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.5 ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  4.34,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.61,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.2 ,  0.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  3.23,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.31,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.  ,  1.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  2.05,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  3.35,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.21,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  1.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.  ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.88,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.71,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  4.  ,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  2.5 ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.02,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  1.83,  0.  ,  0.  ,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  ,  1.5 ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  1.96,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.56,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.61,  0.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  5.  ,  1.  ,  0.  ,  1.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.97,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.41,  1.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  3.25,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.06,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.45,  0.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  4.3 ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  1.36,  0.  ,  0.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  3.18,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  3.  ,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  2.5 ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.18,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.75,  0.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  2.  ,  1.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  2.01,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  ,  2.71,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  4.  ,  1.  ,  1.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.92,  1.  ,  1.  ,  1.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  ,  1.32,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  1.5 ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.31,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.25,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  1.71,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.  ,  1.  ,  0.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  ,  5.  ,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  3.23,  0.  ,  1.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.1 ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.83,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.34,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  2.5 ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  6.7 ,  1.  ,  0.  ,  1.  ,  6.  ],
       [ 0.  ,  0.  ,  0.  ,  2.  ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  3.12,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  3.  ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.64,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.3 ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.5 ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.67,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  5.16,  1.  ,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  4.67,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.5 ,  0.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.24,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  1.8 ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.58,  1.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  2.23,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.25,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  1.73,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  2.  ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.75,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.  ,  1.  ,  0.  ,  0.  ,  6.  ],
       [ 0.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  3.92,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.44,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.5 ,  1.  ,  0.  ,  0.  ,  2.  ]])

In [ ]:
x_test = ct.transform(x_test)
x_test

ValueError: X has 8 features, but ColumnTransformer is expecting 6 features as input.

In [ ]:
## SVR Model
from sklearn.svm import SVR
model = SVR()

In [ ]:
model.fit(x_train, y_train)

SVR()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(r2_score(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))

0.35601683959928343
5.57163825689048
62.16159354115723

In [ ]:
# Hyperparameter Tuning

from sklearn.model_selection import GridSearchCV
# defined parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]}

In [ ]:
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3)

# fitting the model for grid search
grid.fit(x_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ...................C=0.1, gamma=1;, score=-0.185 total time=   0.0s
[CV 2/5] END ...................C=0.1, gamma=1;, score=-0.080 total time=   0.0s
[CV 3/5] END ...................C=0.1, gamma=1;, score=-0.004 total time=   0.0s
[CV 4/5] END ...................C=0.1, gamma=1;, score=-0.028 total time=   0.0s
[CV 5/5] END ....................C=0.1, gamma=1;, score=0.039 total time=   0.0s
[CV 1/5] END .................C=0.1, gamma=0.1;, score=-0.073 total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.1;, score=0.111 total time=   0.0s
[CV 3/5] END ..................C=0.1, gamma=0.1;, score=0.087 total time=   0.0s
[CV 4/5] END ..................C=0.1, gamma=0.1;, score=0.093 total time=   0.0s
[CV 5/5] END ..................C=0.1, gamma=0.1;, score=0.176 total time=   0.0s
[CV 1/5] END ................C=0.1, gamma=0.01;, score=-0.177 total time=   0.0s
[CV 2/5] END ................C=0.1, gamma=0.01;, score=-0.041 total time=   0.0s
[CV 3/5] END ................C=0.1, gamma=0.01;, score=-0.007 total time=   0.0s
[CV 4/5] END ................C=0.1, gamma=0.01;, score=-0.013 total time=   0.0s
[CV 5/5] END .................C=0.1, gamma=0.01;, score=0.054 total time=   0.0s
[CV 1/5] END ...............C=0.1, gamma=0.001;, score=-0.214 total time=   0.0s
[CV 2/5] END ...............C=0.1, gamma=0.001;, score=-0.110 total time=   0.0s
[CV 3/5] END ...............C=0.1, gamma=0.001;, score=-0.043 total time=   0.0s
[CV 4/5] END ...............C=0.1, gamma=0.001;, score=-0.060 total time=   0.0s
[CV 5/5] END ...............C=0.1, gamma=0.001;, score=-0.004 total time=   0.0s
[CV 1/5] END ..............C=0.1, gamma=0.0001;, score=-0.218 total time=   0.0s
[CV 2/5] END ..............C=0.1, gamma=0.0001;, score=-0.118 total time=   0.0s
[CV 3/5] END ..............C=0.1, gamma=0.0001;, score=-0.047 total time=   0.0s
[CV 4/5] END ..............C=0.1, gamma=0.0001;, score=-0.065 total time=   0.0s
[CV 5/5] END ..............C=0.1, gamma=0.0001;, score=-0.011 total time=   0.0s
[CV 1/5] END ......................C=1, gamma=1;, score=0.051 total time=   0.0s
[CV 2/5] END ......................C=1, gamma=1;, score=0.191 total time=   0.0s
[CV 3/5] END ......................C=1, gamma=1;, score=0.191 total time=   0.0s
[CV 4/5] END ......................C=1, gamma=1;, score=0.208 total time=   0.0s
[CV 5/5] END ......................C=1, gamma=1;, score=0.254 total time=   0.0s
[CV 1/5] END ....................C=1, gamma=0.1;, score=0.256 total time=   0.0s
[CV 2/5] END ....................C=1, gamma=0.1;, score=0.602 total time=   0.0s
[CV 3/5] END ....................C=1, gamma=0.1;, score=0.292 total time=   0.0s
[CV 4/5] END ....................C=1, gamma=0.1;, score=0.407 total time=   0.0s
[CV 5/5] END ....................C=1, gamma=0.1;, score=0.587 total time=   0.0s
[CV 1/5] END ...................C=1, gamma=0.01;, score=0.122 total time=   0.0s
[CV 2/5] END ...................C=1, gamma=0.01;, score=0.398 total time=   0.0s
[CV 3/5] END ...................C=1, gamma=0.01;, score=0.184 total time=   0.0s
[CV 4/5] END ...................C=1, gamma=0.01;, score=0.259 total time=   0.0s
[CV 5/5] END ...................C=1, gamma=0.01;, score=0.418 total time=   0.0s
[CV 1/5] END .................C=1, gamma=0.001;, score=-0.166 total time=   0.0s
[CV 2/5] END .................C=1, gamma=0.001;, score=-0.028 total time=   0.0s
[CV 3/5] END .................C=1, gamma=0.001;, score=-0.002 total time=   0.0s
[CV 4/5] END .................C=1, gamma=0.001;, score=-0.006 total time=   0.0s
[CV 5/5] END ..................C=1, gamma=0.001;, score=0.065 total time=   0.0s
[CV 1/5] END ................C=1, gamma=0.0001;, score=-0.213 total time=   0.0s
[CV 2/5] END ................C=1, gamma=0.0001;, score=-0.110 total time=   0.0s
[CV 3/5] END ................C=1, gamma=0.0001;, score=-0.043 total time=   0.0s
[CV 4/5] END ................C=1, gamma=0.0001;, score=-0.060 total time=   0.0s
[CV 5/5] END ................C=1, gamma=0.0001;, score=-0.004 total time=   0.0s
[CV 1/5] END .....................C=10, gamma=1;, score=0.319 total time=   0.0s
[CV 2/5] END .....................C=10, gamma=1;, score=0.459 total time=   0.0s
[CV 3/5] END .....................C=10, gamma=1;, score=0.412 total time=   0.0s
[CV 4/5] END .....................C=10, gamma=1;, score=0.470 total time=   0.0s
[CV 5/5] END .....................C=10, gamma=1;, score=0.355 total time=   0.0s
[CV 1/5] END ...................C=10, gamma=0.1;, score=0.358 total time=   0.0s
[CV 2/5] END ...................C=10, gamma=0.1;, score=0.718 total time=   0.0s
[CV 3/5] END ...................C=10, gamma=0.1;, score=0.359 total time=   0.0s
[CV 4/5] END ...................C=10, gamma=0.1;, score=0.468 total time=   0.0s
[CV 5/5] END ...................C=10, gamma=0.1;, score=0.629 total time=   0.0s
[CV 1/5] END ..................C=10, gamma=0.01;, score=0.373 total time=   0.0s
[CV 2/5] END ..................C=10, gamma=0.01;, score=0.757 total time=   0.0s
[CV 3/5] END ..................C=10, gamma=0.01;, score=0.305 total time=   0.0s
[CV 4/5] END ..................C=10, gamma=0.01;, score=0.429 total time=   0.0s
[CV 5/5] END ..................C=10, gamma=0.01;, score=0.741 total time=   0.0s
[CV 1/5] END .................C=10, gamma=0.001;, score=0.194 total time=   0.0s
[CV 2/5] END .................C=10, gamma=0.001;, score=0.416 total time=   0.0s
[CV 3/5] END .................C=10, gamma=0.001;, score=0.204 total time=   0.0s
[CV 4/5] END .................C=10, gamma=0.001;, score=0.288 total time=   0.0s
[CV 5/5] END .................C=10, gamma=0.001;, score=0.469 total time=   0.0s
[CV 1/5] END ...............C=10, gamma=0.0001;, score=-0.164 total time=   0.0s
[CV 2/5] END ...............C=10, gamma=0.0001;, score=-0.026 total time=   0.0s
[CV 3/5] END ...............C=10, gamma=0.0001;, score=-0.002 total time=   0.0s
[CV 4/5] END ...............C=10, gamma=0.0001;, score=-0.005 total time=   0.0s
[CV 5/5] END ................C=10, gamma=0.0001;, score=0.066 total time=   0.0s
[CV 1/5] END ....................C=100, gamma=1;, score=0.175 total time=   0.0s
[CV 2/5] END ....................C=100, gamma=1;, score=0.363 total time=   0.0s
[CV 3/5] END ....................C=100, gamma=1;, score=0.374 total time=   0.0s
[CV 4/5] END ....................C=100, gamma=1;, score=0.298 total time=   0.0s
[CV 5/5] END ....................C=100, gamma=1;, score=0.381 total time=   0.0s
[CV 1/5] END ..................C=100, gamma=0.1;, score=0.430 total time=   0.0s
[CV 2/5] END ..................C=100, gamma=0.1;, score=0.604 total time=   0.0s
[CV 3/5] END ..................C=100, gamma=0.1;, score=0.293 total time=   0.0s
[CV 4/5] END ..................C=100, gamma=0.1;, score=0.400 total time=   0.0s
[CV 5/5] END ..................C=100, gamma=0.1;, score=0.435 total time=   0.0s
[CV 1/5] END .................C=100, gamma=0.01;, score=0.407 total time=   0.0s
[CV 2/5] END .................C=100, gamma=0.01;, score=0.724 total time=   0.0s
[CV 3/5] END .................C=100, gamma=0.01;, score=0.349 total time=   0.0s
[CV 4/5] END .................C=100, gamma=0.01;, score=0.452 total time=   0.0s
[CV 5/5] END .................C=100, gamma=0.01;, score=0.711 total time=   0.0s
[CV 1/5] END ................C=100, gamma=0.001;, score=0.423 total time=   0.0s
[CV 2/5] END ................C=100, gamma=0.001;, score=0.765 total time=   0.0s
[CV 3/5] END ................C=100, gamma=0.001;, score=0.301 total time=   0.0s
[CV 4/5] END ................C=100, gamma=0.001;, score=0.427 total time=   0.0s
[CV 5/5] END ................C=100, gamma=0.001;, score=0.750 total time=   0.0s
[CV 1/5] END ...............C=100, gamma=0.0001;, score=0.202 total time=   0.0s
[CV 2/5] END ...............C=100, gamma=0.0001;, score=0.421 total time=   0.0s
[CV 3/5] END ...............C=100, gamma=0.0001;, score=0.206 total time=   0.0s
[CV 4/5] END ...............C=100, gamma=0.0001;, score=0.292 total time=   0.0s
[CV 5/5] END ...............C=100, gamma=0.0001;, score=0.475 total time=   0.0s
[CV 1/5] END ...................C=1000, gamma=1;, score=0.115 total time=   0.0s
[CV 2/5] END ...................C=1000, gamma=1;, score=0.133 total time=   0.0s
[CV 3/5] END ...................C=1000, gamma=1;, score=0.143 total time=   0.0s
[CV 4/5] END ...................C=1000, gamma=1;, score=0.230 total time=   0.0s
[CV 5/5] END ...................C=1000, gamma=1;, score=0.328 total time=   0.0s
[CV 1/5] END .................C=1000, gamma=0.1;, score=0.178 total time=   0.0s
[CV 2/5] END ................C=1000, gamma=0.1;, score=-0.228 total time=   0.0s
[CV 3/5] END .................C=1000, gamma=0.1;, score=0.041 total time=   0.0s
[CV 4/5] END .................C=1000, gamma=0.1;, score=0.104 total time=   0.0s
[CV 5/5] END .................C=1000, gamma=0.1;, score=0.009 total time=   0.1s
[CV 1/5] END ................C=1000, gamma=0.01;, score=0.445 total time=   0.0s
[CV 2/5] END ................C=1000, gamma=0.01;, score=0.685 total time=   0.0s
[CV 3/5] END ................C=1000, gamma=0.01;, score=0.336 total time=   0.0s
[CV 4/5] END ................C=1000, gamma=0.01;, score=0.438 total time=   0.0s
[CV 5/5] END ................C=1000, gamma=0.01;, score=0.588 total time=   0.0s
[CV 1/5] END ...............C=1000, gamma=0.001;, score=0.438 total time=   0.0s
[CV 2/5] END ...............C=1000, gamma=0.001;, score=0.747 total time=   0.0s
[CV 3/5] END ...............C=1000, gamma=0.001;, score=0.342 total time=   0.0s
[CV 4/5] END ...............C=1000, gamma=0.001;, score=0.461 total time=   0.0s
[CV 5/5] END ...............C=1000, gamma=0.001;, score=0.738 total time=   0.0s
[CV 1/5] END ..............C=1000, gamma=0.0001;, score=0.428 total time=   0.0s
[CV 2/5] END ..............C=1000, gamma=0.0001;, score=0.765 total time=   0.0s
[CV 3/5] END ..............C=1000, gamma=0.0001;, score=0.301 total time=   0.0s
[CV 4/5] END ..............C=1000, gamma=0.0001;, score=0.429 total time=   0.0s
[CV 5/5] END ..............C=1000, gamma=0.0001;, score=0.751 total time=   0.0s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             verbose=3)

In [ ]:
grid.best_params_

{'C': 1000, 'gamma': 0.001}

In [ ]:
grid_predictions = grid.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(r2_score(y_test, grid_predictions))
print(mean_absolute_error(y_test, grid_predictions))
print(mean_squared_error(y_test, grid_predictions))

0.48291299027748014
5.088540221833587
49.91272210252026