<a href="https://colab.research.google.com/github/GautamChy/Data-Science-Journey/blob/main/PandasDay02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# create new data
employees = pd.DataFrame({
    'emp_id' : [1,2,3,4],
    'name' : ['Ramesh','Rajesh','Rabin','Ram'],
    'dept_id' : [10,20,30,40]
})

In [ ]:
# create new data
departments = pd.DataFrame({
    'dept_id' : [10,20,40],
    'dept_name' : ['HR','IT','Finance']
})

In [ ]:
employees

   emp_id    name  dept_id
0       1  Ramesh       10
1       2  Rajesh       20
2       3   Rabin       30
3       4     Ram       40

In [ ]:
departments

   dept_id dept_name
0       10        HR
1       20        IT
2       40   Finance

In [ ]:
# Inner - only matching rows from both tables
pd.merge(employees, departments, on = 'dept_id', how = 'inner')

   emp_id    name  dept_id dept_name
0       1  Ramesh       10        HR
1       2  Rajesh       20        IT
2       4     Ram       40   Finance

In [ ]:
# Left - all rows from left, matched rows from right (NaN if no match)
pd.merge(employees, departments, on = 'dept_id', how = 'left')

   emp_id    name  dept_id dept_name
0       1  Ramesh       10        HR
1       2  Rajesh       20        IT
2       3   Rabin       30       NaN
3       4     Ram       40   Finance

In [ ]:
# Right - all rows from right table
pd.merge(employees, departments, on = 'dept_id', how = 'right')

   emp_id    name  dept_id dept_name
0       1  Ramesh       10        HR
1       2  Rajesh       20        IT
2       4     Ram       40   Finance

In [ ]:
# Outer - all rows from both tables
pd.merge(employees, departments, on = 'dept_id', how = 'outer')

   emp_id    name  dept_id dept_name
0       1  Ramesh       10        HR
1       2  Rajesh       20        IT
2       3   Rabin       30       NaN
3       4     Ram       40   Finance

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('constituencywise_details India.csv')
df.head()

,S.N.,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes,Constituency ID
0,1,DR JITENDRA SINGH,Bharatiya Janata Party,566833,4243,571076,51.28,U084
1,2,CH LAL SINGH,Indian National Congress,444151,2552,446703,40.11,U084
2,3,GHULAM MOHD SAROORI,Independent,39519,80,39599,3.56,U084
3,4,MEHRAJ DIN,Independent,9055,27,9082,0.82,U084
4,5,AMIT KUMAR,Bahujan Samaj Party,8559,83,8642,0.78,U084

In [ ]:
df = pd.read_csv('Refined_COVID19_BPS.csv')
df.head()

,Country,Year,Month,Date,Breakdown_Type,Breakdown_Category,Percentage
0,Afghanistan,2020,6,2020-06,Firm Size,Size: Large (100+),2.38
1,Afghanistan,2020,6,2020-06,Firm Size,Size: Large (100+),73.81
2,Afghanistan,2020,6,2020-06,Firm Size,Size: Large (100+),-60.55
3,Afghanistan,2020,6,2020-06,Firm Size,Size: Large (100+),87.50
4,Afghanistan,2020,6,2020-06,Firm Size,Size: Large (100+),-21.49

In [ ]:
df = pd.read_csv('GoldUSD.csv')
df.head()

       Date        Open        High         Low       Close  Volume
0  30-08-00  273.899994  273.899994  273.899994  273.899994       0
1  31-08-00  274.799988  278.299988  274.799988  278.299988       0
2  01-09-00  277.000000  277.000000  277.000000  277.000000       0
3  05-09-00  275.799988  275.799988  275.799988  275.799988       2
4  06-09-00  274.200012  274.200012  274.200012  274.200012       0

In [ ]:
# cocat() - Staciing Dataframes
df_cons_d_india = pd.read_csv('constituencywise_details India.csv')
df_covid = pd.read_csv('Refined_COVID19_BPS.csv')
df_Gold = pd.read_csv('GoldUSD.csv')

In [ ]:
df_cons_d_india.head()

In [ ]:
df_covid.head()

In [ ]:
df_Gold.head()

In [ ]:
df_cons_d_india.shape

In [ ]:
df_covid.shape

In [ ]:
df_Gold.shape

In [ ]:
import pandas as pd

In [ ]:
df_all = pd.concat([df_cons_d_india,df_covid, df_Gold ], ignore_index = True)

In [ ]:
df_all.shape    # added all shape of the df_cons_d_india.shape,df_covid.shape,df_Gold.shape. NOTE = Right side ko value rows and left side ko value column

In [ ]:
# Stack columns horizontally
df_wide = pd.concat([df_])